// <auto-generated />
namespace Dehyari.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RelationPEsronHesabToDehyariHesab5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationPEsronHesabToDehyariHesab5));
        
        string IMigrationMetadata.Id
        {
            get { return "202303020756432_RelationPEsronHesabToDehyariHesab5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
